import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import UseWalletLayout from "../components/UseWalletLayout";
import PageLayout from "../components/PageLayout";
import { useWallet } from "../hooks/useWallet";

const Home: NextPage = () => {
  const { currentAccount, connectWallet } = useWallet();
  return (
    <PageLayout home>
      <UseWalletLayout
        currentAccount={currentAccount}
        connectWallet={connectWallet}
      >
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <h1 className={styles.title}>Welcome to Messenger !</h1>

            <div className={styles.grid}>
              <Link href="/message/SendMessagePage" className={styles.card}>
                <h2>send message &rarr;</h2>
              </Link>
            </div>

            <div className={styles.grid}>
              <Link href="/message/ConfirmMessagePage" className={styles.card}>
                <h2>confirm message &rarr;</h2>
              </Link>
            </div>
          </main>
        </div>
      </UseWalletLayout>
    </PageLayout>
  );
};

export default Home;
